name: Rust
# https://github.com/rust-build/rust-build.action

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
   
      - name: Publish package
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f *.zip
          git commit -m 'uploading binaries'
          git push          
